include ../../../Makefile.cfg

CC = $(CONF_CC)
CFLAGS = $(CONF_CFLAGS)
LD_FLAGS = $(CONF_LDFLAGS)

all: $(notdir $(CURDIR)).elf

%.elf: %.c *.c $(ADD_SOURCES)
	$(CC) $(CFLAGS) $^ -o $@ $(LD_FLAGS)


#$(notdir $(CURDIR)): *.c
#	$(CC) $(CFLAGS) $^ -o $@ $(LDFLAGS)


clean:
	rm -f *.o $(notdir $(CURDIR)).elf
